### ISSUE TITLE
Emacs support

### ISSUE THREAD

**Issue by MagB93** [hansec/fortran-language-server#38]
I'm happy to announce that I created a package for Emacs support for the language server.
You can find it on [lsp-fortran](https://github.com/MagB93/lsp-fortran). I had help from @yyoncho regarding 
some debugging, so thank you again for helping me out.
Currently I'll try to get it on [Melpa](https://melpa.org/#/) put that may take a while and I will report when 
that's occurred.
Could you add a mention of the package in the README.md?

**Comment by hansec** [comment]
Done!

**Comment by MagB93** [comment]
Just for the sake of completion the melpa-merge-request still isn't accepted/review yet. The status is available here https://github.com/melpa/melpa/pull/5722

**Comment by MagB93** [comment]
https://github.com/melpa/melpa/pull/5722 just got merged!
