### ISSUE TITLE
Change request failed for file

### ISSUE THREAD

**Issue by Edmundod** [hansec/fortran-language-server#41]
Dear Chris,

thank you for the fortls and ide-fortran.

I run into a problem with non-english letters used in a code. When I modify a line containing special characters from my native language, which I use in comments, fortls gives me the following error:

`Change request failed for file "<here is path to a file>": Could not apply change`

Any idea if this can be repaired?

Greetings!

**Comment by hansec** [comment]
Thanks for the report. I thought I had it working for all unicode characters. Can you post an example file to this issue so I can check it out? Thanks!

**Comment by Edmundod** [comment]
Of course, here is the example, which gives me the error:
```
program test

  ! ąćęłóśźż 

end program test
```

**Comment by hansec** [comment]
Hmmm, I am unable to reproduce this error using the program above. What OS and version of Python are you using? You are seeing the error in Atom, right?

One other thought I had is maybe the characters got translated to Unicode in this issue. Can you verify that if you copy/paste the program above into your editor from this issue it still produces the error?

**Comment by Edmundod** [comment]
Yes, I am using Atom 1.30.0 on Linux with Fortls v 0.8.2. `pip --version` gives me 

```pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)```.

I got the error also copy-pasting test program from this discussion, here is screenshot:
![fortls](https://user-images.githubusercontent.com/29704473/45257057-d0db3900-b39f-11e8-95f6-3245502c127d.png)

How can I investigate further? Maybe some logs from fortls?

**Comment by hansec** [comment]
Ok, I am going to add some additional functionality to log information about errors like this. Hopefully, that will help us track down the issue. In the meantime can you try disabling incremental synchronization and see if you still get the error? Note that you need to restart Atom after changing this setting in the `ide-fortran` extension for the change to take effect.

**Comment by hansec** [comment]
I have just released a new version of the language server (0.8.3) that includes the ability to generate debugging logs. You can enable this feature using the setting `debug_log` in the `.fortls` settings file in your project root directory. See the [README](https://github.com/hansec/fortran-language-server/blob/master/README.rst#configuration) for more information. Can you please run the case above with this setting enabled and post the resulting log file?

**Comment by Edmundod** [comment]
Great, I have some error which tracebacks to langserver.py. Here is the log: [fortls_debug_with_incremental.log](https://github.com/hansec/fortran-language-server/files/2365502/fortls_debug_with_incremental.log)

Disabling incremental synchronization turned off the error.

**Comment by Edmundod** [comment]
And it probably says about position 4 because now I used one letter, which is in 4th column:

`  ! ą`

**Comment by hansec** [comment]
Ok, I just released (0.8.4) what I believe is a fix to this bug. Check it out and let me know if the problem persists. Thanks again for the report!

**Comment by Edmundod** [comment]
The problem is solved. Thank you very much for all the effort.

**Comment by liuyapeng1996** [comment]
Using vscode and Modern Fortran on windows, this error still occurs: Change request failed for file “xx\xx\xx\xx\*.f90”: Could not apply change. Source: Modern Fortran (Extension).
