### ISSUE TITLE
Varaibale name beginning with "end"

### ISSUE THREAD

**Issue by HaritzGarai** [hansec/fortran-language-server#73]
When I open atom I get the following error message:
```
Initialization failed for file "/home/user/Code/src/parameters.F90": Error during parsing
Fortran (fortls) /home/user/Code/
```

To see what is happening I tried to run fortls from the terminal:
`fortls --debug_parser --debug_filepath parameters.F90`

And I get the following output:
```
end_st='end '//trim(keyword) !!! END "" scope(2206)
Traceback (most recent call last):
  File "/home/user/.local/bin/fortls", line 11, in <module>
    load_entry_point('fortran-language-server==1.0.1', 'console_scripts', 'fortls')()
  File "/home/user/.local/lib/python2.7/site-packages/fortls/__init__.py", line 137, in main
    ast_new = process_file(contents_split, True, fixed_format=fixed_flag, debug=True)
  File "/home/user/.local/lib/python2.7/site-packages/fortls/parse_fortran.py", line 746, in process_file
    file_obj.add_scope(new_do, END_DO_WORD, req_container=True)
  File "/home/user/.local/lib/python2.7/site-packages/fortls/objects.py", line 1052, in add_scope
    self.create_none_scope()
  File "/home/user/.local/lib/python2.7/site-packages/fortls/objects.py", line 1039, in create_none_scope
    raise ValueError
ValueError
```

It seems that the problem is the variable named `end_st`. Changing its name the problem disappears.

I have repeated the same test with different versions of fortran-language-server. The problem is not present in version 0.9.3. It appears in versions 1.0.0 and 1.0.1.

OS: Ubuntu 18.04 LTS

**Comment by hansec** [comment]
Thanks for the report! I just pushed a fix to this issue that will be included in the next patch (probably tomorrow).

**Comment by HaritzGarai** [comment]
The problem is still present if the assignation is separated from the variable name, like in this example:
`end_q = start_q + (Nper - 1)`

The output of fortls is:
```
end_q = start_q + (Nper - 1) !!! END "_Q" scope(346)
Traceback (most recent call last):
  File "/home/user/.local/bin/fortls", line 11, in <module>
    load_entry_point('fortran-language-server==1.0.2', 'console_scripts', 'fortls')()
  File "/home/user/.local/lib/python2.7/site-packages/fortls/__init__.py", line 137, in main
    ast_new = process_file(contents_split, True, fixed_format=fixed_flag, debug=True)
  File "/home/user/.local/lib/python2.7/site-packages/fortls/parse_fortran.py", line 756, in process_file
    file_obj.add_scope(new_do, END_DO_WORD, req_container=True)
  File "/home/user/.local/lib/python2.7/site-packages/fortls/objects.py", line 1063, in add_scope
    self.create_none_scope()
  File "/home/user/.local/lib/python2.7/site-packages/fortls/objects.py", line 1050, in create_none_scope
    raise ValueError
ValueError
```

I think that could be corrected changing the regular expression `END_WORD_REGEX` from file fortls/parse_fortran.py:
from `END_WORD_REGEX = re.compile(r'[ ]*END[ ]*([_a-z]*|$)', re.I)`
to `END_WORD_REGEX = re.compile(r'[ ]*END[ ]*([_a-z]*|$)[ ]*', re.I)`

I do not know if this is the most appropriate solution, but works for this particular example.

**Comment by hansec** [comment]
Ooops, thanks! Yes, I was a little sloppy and didn't check any variations on the case you gave me. I believe I have now corrected this, along with another case I was missing. I will release a patch later today, let me know if you run into any more issues. Thanks!

**Comment by emanspeaks** [comment]
I don't believe this is fixed, as I am running into a problem now where a file contains a variable called `ENDS`.  Walking through things with a debugger, it looks like the last `if` statement in the scope stack has one of these ENDS assignment lines marked as the end line of the `if` scope erroneously.  The next attempt to create a scope for a do block that follows is resulting in a ValueError from `create_none_scope`

**Comment by hansec** [comment]
@emanspeaks I just changed the way I discriminate between variables and end statements to a method that is hopefully more robust. Can you give me some example code of the case where you saw this error so I can test it? Alternatively, you can checkout the newest version in master and see if that fixes your issue. Thanks for the report!

**Comment by emanspeaks** [comment]
Whoops, I had been working from the master branch, but realized I haven't pulled since you pushed the fix.  This made a LOT of my errors go away in the latest version.  Thanks!  Sorry for the false alarm!
